### ISSUE TITLE
Lobbyist list pagination overlaps HR

### ISSUE THREAD

**Issue by laureenas** [ManoSeimas/manoseimas.lt#102]
**Steps to reproduce**:
- Go to manoseimas.lt
- Click "Lobistai"
- Click on the name of a Lobbyist, e.g. http://www.manoseimas.lt/lobbyists/lobbyist/uab-vento-nuovo

**Expected results**:

Pagination buttons show up above the horizontal rule.

**Actual results**:

Pagination buttons overlap  the horizontal rule.

See image below:

![image](https://cloud.githubusercontent.com/assets/4104268/10576491/55138818-766c-11e5-9ea0-8b6caf783958.png)

**Comment by mgedmin** [comment]
I thought that was intentional :)  It looks kinda cool.
