### ISSUE TITLE
Lobistų sąraše pateikiami skaičiukai yra nuorodos į detales ataskaitas

### ISSUE THREAD

**Issue by laureenas** [ManoSeimas/manoseimas.lt#105]
Padaryti, kad ant lobistų sąraše pateikiamų skaičiukų irgi atsirastų hyperlink į detales ataskaitas? ty. kad paspaudus ant UAB "Vento Nuovo" skaičiaus 55 atsidarytų tas pats langas kaip ir ant jų pavadinimo paspaudus?

**Comment by mgedmin** [comment]
O kaip dėl teksto, esančio po skaičiuku?

**Comment by laureenas** [comment]
Manau, reiktų ir skaičiuoką, ir tekstą. Kai dariau prototipą, dariau du atskirus <a />
