### ISSUE TITLE
Set up a staging site for manoseimas.lt

### ISSUE THREAD

**Issue by mgedmin** [ManoSeimas/manoseimas.lt#120]
It's not nice that we have to deploy to production and risk breaking things in order to show or test work-in-progress.

Plan:
- [x] pick a hostname (manoseimas-staging.pov.lt)
- [x] pick a server (iv-5.pov.lt)
- [x] set up DNS
- [x] update Ansible configs to make it deployable
- [x] deploy
- [ ] remove sirex from django admins to avoid mail floods

**Comment by mgedmin** [comment]
Oh look, we already have mysql running on iv-4.  Yay.

**Comment by mgedmin** [comment]
Things to watch out for:

- manoseimas wants to overwrite the mysql root password and clobber /root/.my.cnf; will this break any of the already-deployed sites on iv-4?

**Comment by mgedmin** [comment]
Roablock:
- `iv-4` has libapache2-mod-wsgi-py3 because atviriduomenys.lt requires Python 3
- you cannot install both libapache2-mod-wsgi and libapache2-mod-wsgi-py3
- manoseimas.lt doesn't support Python 3

What do we do?

Options:
- ~~deploy manoseimas-staging.pov.lt on iv-2~~ (iv-2 has Ubuntu 12.04 and manoseimas probably requires 14.04)
- rent a new virtual server for manoseimas-staging.pov.lt
- rewrite deployment so we can deploy manoseimas-staging.pov.lt on the same server as manoseimas.lt (i.e. don't hardcode mysql and couchdb database names, deployment directory names, apache log directory names)
- port manoseimas.lt to Python 3
- port atviriduomenys.lt and pylab.lt and manopozicija.lt to Python 2.7
- rewrite manoseimas.lt deployment to use uwsgi/gunicorn/waitress/some other web server that isn't mod_wsgi

cc: @sirex @laureenas

**Comment by sirex** [comment]
I guess fastest and cheapest solution would be to rent a new server? Since you need it just for few weeks?

**Comment by sirex** [comment]
By the way, iv-4.pov.lt hosts more projects: https://github.com/akllt/infrastructure/tree/master/websites

**Comment by mgedmin** [comment]
Yeah, I updated https://fridge.pov.lt/sysadmin/servers/iv-4.html#sites-hosted-here yesterday.

Only three use mod_wsgi: atviriduomenys.lt, pylab.lt, manopozicija.lt.

**Comment by mgedmin** [comment]
We'll use iv-5 (a new server) for this.

**Comment by mgedmin** [comment]
Currently Django error emails are configured to go to sirexas@gmail.com.

The current manoseimas.lt production server has broken email delivery so they don't go anywhere.

Vagrant doesn't have a local MTA so in our dev sandboxes the emails don't go anywhere.

iv-5 has working email delivery, so @sirex will start receiving error emails from staging, unless we change the admin email address to something else.

Opinions?

**Comment by sirex** [comment]
I think, best think would be to forward all errors to POV's Sentry server? And leave list of admins empty?

**Comment by mgedmin** [comment]
+1 for sentry

**Comment by mgedmin** [comment]
http://manoseimas-staging.pov.lt/ is deployed, now waiting for the crawlers to crawl some data (and showing Internal Server Errors to anyone because #61).
