### ISSUE TITLE
Save user voting results

### ISSUE THREAD

**Issue by chompomonim** [ManoSeimas/manoseimas.lt#151]
* [x] Automatically create user session for unauthenticated users on first 'save question answer(s)' api call.
* [x] Associate unauthenticated user's session when he is logging in/creating account.
* [x] Solve API calls (save/get) security using authorisation (in any way you choose)

**Comment by menesis** [comment]
Users are created on demand, identified by a cookie.
There is a `convert` view that is not hooked up, to convert lazy user to permanent user with a username.
