### ISSUE TITLE
Get list of Questions

### ISSUE THREAD

**Issue by chompomonim** [ManoSeimas/manoseimas.lt#153]
API call which returns list of current test questions with their meta data (title, description, arguments)
Questions should be randomised but group in political topics groups. All topics with one group should go one after another.

**Comment by sirex** [comment]
An example json would be useful. As I understood it should look something like this:
```
[[{... topic ...}, ...], ...]
```
?

**Comment by chompomonim** [comment]
Yes, I think it could be:

```
[ { 
  id: ...,
  group: ...,
  title: ...,
  description: ...,
  arguments: [{
     id: ...,
     title: ...,
     description: ...,
     positive: boolean
  }, {...}],
  votings: [{
     id: ...,
     title: ...,
     url: ..., // To LRS website
  }, {...}]
}, {
...
}]
```

**Comment by menesis** [comment]
I have added `votings` to the topic, but it should be `positions` instead. But that is not precomputed yet #155
