### ISSUE TITLE
Update deployment scripts to support npm/webpack bundled js

### ISSUE THREAD

**Issue by chompomonim** [ManoSeimas/manoseimas.lt#156]

**Comment by frgtn** [comment]
Deployment breaks with Ansible 2.1 due to https://docs.ansible.com/ansible/become.html#becoming-an-unprivileged-user

**Comment by frgtn** [comment]
Installing `acl` package fixed things.

**Comment by frgtn** [comment]
There are also some issues with migrations not working between master and the `new_test` branch which I'm not going to investigate now.

**Comment by frgtn** [comment]
Ended up having to investigate said migration rpoblems. Looks like [compatibility_test/0002_..](https://github.com/ManoSeimas/manoseimas.lt/blob/new_test/manoseimas/compatibility_test/migrations/0002_auto_20160531_1913.py) breaks when trying to do a rename.
