### ISSUE TITLE
Getting  403 (FORBIDDEN) on POST request for /json/answers

### ISSUE THREAD

**Issue by chompomonim** [ManoSeimas/manoseimas.lt#168]
Getting 403 (FORBIDDEN) when calling into http://localhost:8000/test/json/answers
Get request returns `{}`.

Should I post any special stuff in POST request in terms of being authorised using lazy_user? Any examples for proper AJAX request?

**Comment by chompomonim** [comment]
It seems that problem is with CSRF token.

```
<p>Reason given for failure:</p>
            <pre>
    CSRF token missing or incorrect.
    </pre>
            <p>In general, this can occur when there is a genuine Cross Site Request Forgery, or when
  
                <a
  href="https://docs.djangoproject.com/en/1.8/ref/csrf/">Django's
  CSRF mechanism</a> has not been used correctly.
```

Now the question is, how to get this token?

**Comment by sirex** [comment]
How to pass csrf token is well described here: https://docs.djangoproject.com/en/1.8/ref/csrf/#ajax

**Comment by chompomonim** [comment]
I had to add ''X-CSRFToken" into RequestHeader.
