### ISSUE TITLE
Test v2 staging

### ISSUE THREAD

**Issue by sirex** [ManoSeimas/manoseimas.lt#176]
Create a staging.manoseimas.lt instance on the same server as manoseimas.lt.

Each deployment should create copy of production database and apply migrations on top of it, removing all staging database data.

**Comment by chompomonim** [comment]
I would just reuse current PoV staging:
manoseimas-staging.pov.lt

**Comment by sirex** [comment]
Padeployinta, veikia: http://manoseimas-staging.pov.lt/test/
