### ISSUE TITLE
Problem with newly created fractions

### ISSUE THREAD

**Issue by chompomonim** [ManoSeimas/manoseimas.lt#184]
LLRA just changes theyir name to Lietuvos lenkų rinkimų akcijos-Krikščioniškų šeimų sąjungos frakcija (LLRAKŠS), so in our database we have both fractions. The problem is that LLRAKŠS is getting {..., answets: null, ...}. 

@sirex Do you have any ideas how to solve such problem?

**Comment by sirex** [comment]
> The problem is that LLRAKŠS is getting {..., answets: null, ...}.

Why this is a problem?
