### ISSUE TITLE
BUG: We're still getting  NaN% for LLRA-KŠSF and TS-LKDF

### ISSUE THREAD

**Issue by chompomonim** [ManoSeimas/manoseimas.lt#217]
It's because scrapy is looking over fraction short name in parliament voting page. And in DB it's just getting name and trying to create abbreviation.

Also LLRA just change name, so we're loosing either new either old their votes :/

**Comment by sirex** [comment]
Did your [change](https://github.com/ManoSeimas/manoseimas.lt/commit/043cc910e5a7674a9e6c85c87e6d8640882ec32c) fixed the bug?

**Comment by chompomonim** [comment]
It helps, but I also have to write migration to fix all old votes where there are already fraction names with '-' or delete all votes and run scrappy again :/
