### ISSUE TITLE
Create a database schema for lobbyist declarations

### ISSUE THREAD

**Issue by laureenas** [ManoSeimas/manoseimas.lt#50]
Create database schema to store scraped data of lobbyist declarations.

For relevant fields see #48, #49.

Use MySQL as CouchDB is deprecated. 

Relates to story: #43.

**Comment by mgedmin** [comment]
Things we can learn about lobbyists (see #48):

- **Name** (e.g. "BRONIUS ANTANAS RASIMAS" or "UAB "ERNST & YOUNG BALTIC")
- **URL** (e.g. "http://www.ey.com/GLOBAL/content.nsf/Lithuania_E/Lithuania_Home"; optional)
- Names of **representatives** (e.g. "Gintautas Bartkus, Jonas"; optional)
- **Company code** (e.g. "1087844"; optional)
- **Date of inclusion** into the list of lobbyists (e.g. "2001 01 24")
- **Number of the decision** to include in the list of lobbyists on that date (e.g. "Nr. 18 (L)")
- **Status** (e.g. "2015 03 04 sprendimu Nr. KS-20 (L) sustabdyta lobistinė veikla iki prašymo atnaujinti.", "2015-04-15 sprendimu Nr. KS-31 (L) lobistinė veikla nutraukta."; optional)

**Comment by mgedmin** [comment]
Lobbyist declarations (#49):

- **Year** (e.g. "2014")
- **Name** (e.g. "BRONIUS ANTANAS RASIMAS" or "UAB "ERNST & YOUNG BALTIC")
- **Client** (e.g. "Lietuvos kabelinės televizijos asocijacija" or "-")
- **Law project** (e.g. "1. Lietuvos Respublikos visuomenės informavimo įstatymo projektas." or "-")
- **Comments** (e.g. "Lobistinės veiklos nevykdė")
