### ISSUE TITLE
Scrape motion backers

### ISSUE THREAD

**Issue by laureenas** [ManoSeimas/manoseimas.lt#73]
We are interested in other bodies besides 'Seimo nariai' under clause 'Teikia'. [1]

Perhaps 

 - [ ] scrape 'Teikia'
 - [ ] see whether there is data on other bodies than MPs
 - [ ] store other bodies than MPs in a DB.

[1]
![image](https://cloud.githubusercontent.com/assets/4104268/10041821/da662b60-61ef-11e5-9232-48256151c05e.png)

Relates to story #43

**Comment by frgtn** [comment]
Currently manoseimas scrapes law project data from individual MP project pages, not from law projects themselves.

**Comment by frgtn** [comment]
Actual source: http://www3.lrs.lt/pls/inter/w5_smn_akt_new.seim_nar_proj?p_kad_ses=k7&p_start=2012-11-16

**Comment by laureenas** [comment]
Superseded by #83 

Client does not seem to be interested in Teikėjai. Probable reason is that Teikėjai are accounted for under what MP provides motions with what other MPs.
