### ISSUE TITLE
Scrape motion commenters

### ISSUE THREAD

**Issue by laureenas** [ManoSeimas/manoseimas.lt#83]
Some motions have one or more commenter (pasiūlymo teikėjas).

Perhaps we scrape all comments. 

Fields of interest: 
 - pasiūlymo teikėjas (svarbu), 
 - pasiūlymo data (jei pigu - PK dalis),
 - pasiūlymo turinys (jei labai pigu - tai tik papildoma info),
 - komiteto nuomonė (svarbu)

![image](https://cloud.githubusercontent.com/assets/4104268/10315089/d8c52fa6-6c60-11e5-829e-0b00e48cb95e.png)

[1] http://www3.lrs.lt/pls/inter3/dokpaieska.showdoc_l?p_id=1079143&p_tr2=2

Relates to story #43.

**Comment by mgedmin** [comment]
> pasiūlymo data (jei pigu - PK dalis),

Ką reiškia "PK"?

**Comment by laureenas** [comment]
PK - Primary Key

**Comment by mgedmin** [comment]
I'm trying to put this into context.

The description links to an example document.  How can I get the list of documents to scrape?  Are they already being scraped by one of the existing spiders, for other purposes?

**Comment by laureenas** [comment]
Just use 'Rūšis: Komiteto išvada' (as insuficiently marked on the creenshot). Or, I believe, the same can be achieved by this url:

http://www3.lrs.lt/pls/inter3/dokpaieska.rezult_l?p_drus=146

**Comment by mgedmin** [comment]
Ok, let's talk data model.  We have a table (**Suggestions**) with
- **Submitter** (e.g. "Seimo kanceliarijos Teisės departamentas", "Europos Teisės departamentas prie Lietuvos Respublikos Teisingumo ministerijos", "Irena Junevičienė ir
grupė žmonių pasirašiusių dėl motinystės išmokų atstatymo")
- **Date** (e.g. "2014-11-13" or "2014-11")
- **Document ID** (e.g. "XIIP-2492" or "g-2015-7397" or "nutarimas  Nr. 754"; optional)
- **Suggestion** text (multiple paragraphs of text; maybe let's omit this?  can mysql handle long variable-length varchars efficiently?)
- Committee **Opinion** (e.g. "Pritarti"; optional)

**Comment by laureenas** [comment]
Actually it would could be interesting to have the category attached to each suggestion.
Piority: low

Categories seem to be section titles:
- Ekspertų, konsultantų, specialistų išvados, pasiūlymai, pataisos, pastabos
- Piliečių, asociacijų, politinių partijų ir kitų suinteresuotų asmenų pasiūlymai
- Valstybės ir savivaldybių institucijų ir įstaigų pasiūlymai
- Subjektų, turinčių įstatymų leidybos iniciatyvos teisę, pasiūlymai
