### ISSUE TITLE
Add EU support indicator to footer

### ISSUE THREAD

**Issue by laureenas** [ManoSeimas/manoseimas.lt#85]
Ruta Mrazauskaite <ruta@transparency.lt>

Siunčiu tekstą ir logotipą, kurį prašysime įdėti į svetainės apačią, šalia TI logotipo, tekstas po vėliavėle turėtų būti.

Iš dalies finansuojama EK programos „Nusikalstamumo prevencija ir kova su nusikalstamumu“ lėšomis. EK Vidaus reikalų generalinis direktoratas.

There seems to be guidelines for this: http://nvoprograma.lt/lt/projektai/projektu-viesinimo-gaires 

![image](https://cloud.githubusercontent.com/assets/4104268/10337679/156b3514-6d0a-11e5-9ccb-06a602a6979d.png)

**Comment by mgedmin** [comment]
Deployed to production.
