### ISSUE TITLE
Add JSON endpoint for suggesters-state and suggesters-non-state

### ISSUE THREAD

**Issue by laureenas** [ManoSeimas/manoseimas.lt#87]
Client has asked to have separate tabs for government law project suggesters and for NGOs,

Government law project suggesters are: 
 - commissions
 - MPs
 - cabinet
 - ?

**Comment by laureenas** [comment]
We want these to feed through different JSON end points:

`/lobbyists/json/suggesters-state`
`/lobbyists/json/suggesters-non-state`

**Comment by laureenas** [comment]
This should follow #83

**Comment by mgedmin** [comment]
Schema: list of dicts with these keys
- name/title
- number of suggestions
- number of law projects
- success ratio (number of suggestions that were approved)

**Comment by mgedmin** [comment]
Prototype exists in the [suggestion-json-views](https://github.com/ManoSeimas/manoseimas.lt/tree/suggestion-json-views) branch.  Example output:
```
{
    "items": [
        {
            "proposal_count": 8836, 
            "title": "Seimo kanceliarijos Teisės departamentas"
        }, 
        {
            "proposal_count": 1, 
            "title": "Seimo narė A.Stancikienė"
        }, 
...
        {
            "proposal_count": 2, 
            "title": "Lietuvos žmogaus teisių gynimo asociacija"
        }, 
        {
            "proposal_count": 1, 
            "title": "Piliečių gynybos paramos fondas"
        }, 
        {
            "proposal_count": 3, 
            "title": "Seimo narys M. Zasčiurinskas (215-05-29)"
        }, 
        {
            "proposal_count": 2, 
            "title": "Seimo narys M. Zasčiurinskas (215-05-27)"
        }, 
        {
            "proposal_count": 9, 
            "title": "Seimo nariai D. Kuodytė, A. Mazuronis"
        }, 
        {
            "proposal_count": 4, 
            "title": "Seimo nariai R. J. Dagys, L. Kazlavickas, R. Baškienė, A. Stancikienė, M. Zasčiurinskas, A. Dumbrava"
        }
    ]
}
```

Currently there's no categorization into state/non-state actors, and no success estimation.

**Comment by mgedmin** [comment]
I don' t like the proposed URLs.  I suggest rather

    /json/suggesters/?state=yes
    /json/suggesters/?state=no

**Comment by mgedmin** [comment]
The heuristincs function will do for the short term, but long-term we want the users to be able to apply corrections.

Plan:
- [ ] split out a SugesstionSubmitter model with title and is_state_actor fields
- [ ] have the scraper do SugesstionSubmitter.get_or_create(title=title, defaults=dict(is_state_actor=output of the heuristic function)
- [ ] add django admin UI for SuggestionSubmitter so admins can override

**Comment by mgedmin** [comment]
Perhaps the suggestion submitter classifier should have more than two outputs (state vs non-state)?  E.g  we might have "legislative institutions", "executive institutions", "non-government organizations", "private persons".  Or not.  Anyway, do we want to hardcode a boolean when we're changing the database structure?
