### ISSUE TITLE
Add EEA logo to page footer

### ISSUE THREAD

**Issue by laureenas** [ManoSeimas/manoseimas.lt#92]
Add EEA logo to the footer.

http://nvoprograma.lt/lt/projektai/projektu-viesinimo-gaires

EPS file: http://nvoprograma.lt/uploads//EEA_logo.eps

**Comment by mgedmin** [comment]
> **Internetiniai puslapiai**
>
> Kiekviena paramą gaunanti šalis savo puslapyje turi turėti nuorodą į Finansinių
Mechanizmų Valdybos oficialų puslapį. Finansinių mechanizmų adresas
puslapyje turi būti įvestas URL standartu www.eeagrants.com. 

– [Projektų viešinimo gairės](http://nvoprograma.lt/uploads/Projekto%20vie%C5%A1inimo%20gair%C4%97s%20parei%C5%A1k%C4%97jams.pdf)

**Comment by mgedmin** [comment]
> Visada ir visur kur kambama apie projektą privalu naudoti Finansinių
Mechanizmų Valdybos logo. Mažiausias tinkamas naudoti logotipo dydis – 15
mm.

– [Projektų viešinimo gairės](http://nvoprograma.lt/uploads/Projekto%20vie%C5%A1inimo%20gair%C4%97s%20parei%C5%A1k%C4%97jams.pdf)
